apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: foxp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-ztsw-tenant/byoc-app-gviz/foxp@sha256:632e19cd1afe7444e6c2cdace8424422ea34006c9a746ca4cf02b60ed7079c31
        name: my-java-quarkus
        resources: {}
status: {}
